language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kartiktewari9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kartiktewari9/react-test npm run test

after_success:
  - docker build -t kartiktewari9/multi-client ./client
  - docker build -t kartiktewari9/multi-nginx ./nginx   
  - docker build -t kartiktewari9/multi-server ./server   
  - docker build -t kartiktewari9/multi-worker ./worker
  
#Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take these images and push them to docker hub
  - docker push kartiktewari9/multi-client
  - docker push kartiktewari9/multi-nginx 
  - docker push kartiktewari9/multi-server
  - docker push kartiktewari9/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-753171196999"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  